import React, { Component } from 'react'
import PropTypes from 'prop-types'


/**
* @description Represents a shelfer - a dropdown menu do select the status of a book object
* @constructor
*/
class Shelfer extends Component {

	static propTypes = {
		book: PropTypes.object.isRequired,
		onChangeShelf: PropTypes.func.isRequired
	}

	/**
	* @description updates the value of the shelfer and calls the parent component's change function
	* @param {event} e - the change event generated by the select component
	*/
	handleChange = (e) => {
    this.props.onChangeShelf(e.target.value)
    e.preventDefault();
    this.setState({value:e.target.value})
  }

	/**
	* @description stores the current value of the select component
	*/
  state = {
    value:''
  }

	/**
	* @description initialises the value of the select component
	*/
  componentDidMount() {
      this.setState((state) => ({
        value : this.props.book.shelf
      }))
  }


	/**
	* @description drop down menu to select the state a Book component
	*/
	render() {
		return (
			<form onSubmit={this.handleSubmit}>
				<div className="book-shelf-changer">
	        <select value={this.state.value} onChange={this.handleChange} >
	          <option value="none" disabled>Move to...</option>
	          <option value="currentlyReading">Currently Reading</option>
	          <option value="wantToRead">Want to Read</option>
	          <option value="read">Read</option>
	          <option value="none">None</option>
	        </select>
      	</div>
      </form>
	  )
	}
}


export default Shelfer
